version: "3.9"
volumes:
  mongo:
services:
  web:
    # command: tail -f /dev/null
    command: npm start
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app/
  mongo:
    image: mongo:5.0.6
    ports:
      - '27017:27017'
    volumes: 
      - mongo:/data
